### ISSUE TITLE
Data set problem

### ISSUE THREAD

**Issue by Coleddie** [lostmartian/Building-and-Road-Segmentation-from-Aerial-Images#1]
Could you tell me where to download Massachusetts data sets, how to batch download data set on the https://www.cs.toronto.edu/~vmnih/data/

**Comment by lostmartian** [comment]
You can download the datasets from Kaggle

1. [Building Dataset](https://www.kaggle.com/datasets/balraj98/massachusetts-buildings-dataset)
2. [Road Dataset](https://www.kaggle.com/datasets/balraj98/massachusetts-roads-dataset)
